import CollapsibleSidebar from "@/app/components/CollapsibleSidebar";
import type { Metadata } from "next";
import { Geist, Geist_Mono, Roboto } from "next/font/google";
import NextImage from "next/image";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const roboto = Roboto({
  weight: ["300", "400", "500", "700"],
  subsets: ["latin"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <head>
        <link
          href="https://fonts.googleapis.com/icon?family=Material+Icons"
          rel="stylesheet"
        />
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${roboto.className}`}
      >
        <div className="app-container">
          <CollapsibleSidebar />
          <div className="main-content">
            <header className="top-bar">
              <div className="header-content">
                <NextImage
                  src="/blackline.svg"
                  alt="Blackline Logo"
                  className="header-logo"
                  height={400 / 4}
                  width={650 / 4}
                  priority
                />
                <div className="header-actions">
                  <div className="header-item">
                    <span className="material-icons">calendar_today</span>
                    <span>{new Date().toLocaleDateString()}</span>
                  </div>
                  <div className="header-item">
                    <span className="material-icons">notifications</span>
                    <span>Notifications</span>
                  </div>
                  <div className="header-item">
                    <span className="material-icons">list</span>
                    <span>To do list</span>
                  </div>
                  <div className="header-item user-info">
                    <div className="avatar">S</div>
                    <div className="user-details">
                      <div className="role">EXECUTIVE</div>
                      <div>System Administrator</div>
                    </div>
                  </div>
                </div>
              </div>
            </header>
            <main>{children}</main>
          </div>
        </div>
      </body>
    </html>
  );
}
